Fix Security Checker Enlightn Allow List
Error: Allow list didn't work with more than one entry
Caused by: list was passed as "--allow-list=allow_advisory_1,allow_advisory_2" but arguments "--allow-list=allow_advisory_1" "--allow-list=allow_advisory_2" were expected
See: https://github.com/enlightn/security-checker?tab=readme-ov-file#allow-vulnerabilities